// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBalPanHG74-Sh57sBLnZy5FpHqEyKRLUc',
    appId: '1:744625730246:web:511d9b5338a6409a461dc7',
    messagingSenderId: '744625730246',
    projectId: 'fit-friend-a6ea0',
    authDomain: 'fit-friend-a6ea0.firebaseapp.com',
    storageBucket: 'fit-friend-a6ea0.appspot.com',
    measurementId: 'G-3ELFQ9GLMY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAZPqWDg7N4j-dXesOV0XRVbi5jMOzMXak',
    appId: '1:744625730246:android:bf8c6cbab3d1dcdd461dc7',
    messagingSenderId: '744625730246',
    projectId: 'fit-friend-a6ea0',
    storageBucket: 'fit-friend-a6ea0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYmpmo6w1HRaDY7BB0h65vfDddZrk-KHM',
    appId: '1:744625730246:ios:503867b78a011e93461dc7',
    messagingSenderId: '744625730246',
    projectId: 'fit-friend-a6ea0',
    storageBucket: 'fit-friend-a6ea0.appspot.com',
    iosBundleId: 'com.example.modernlogintute',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYmpmo6w1HRaDY7BB0h65vfDddZrk-KHM',
    appId: '1:744625730246:ios:503867b78a011e93461dc7',
    messagingSenderId: '744625730246',
    projectId: 'fit-friend-a6ea0',
    storageBucket: 'fit-friend-a6ea0.appspot.com',
    iosBundleId: 'com.example.modernlogintute',
  );
}
